### ISSUE TITLE
[Cypress] Create test adding more users with different passwords

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#207]
The aim is to create an UI Cypress test that can test login after creating several users with different special characters to always verify this issue: https://github.com/epinio/epinio/issues/1608

After nice converstation with Enrico we managed to create several users with different passwords using a single line command:
```
helm upgrade --install epinio -n epinio --create-namespace epinio/epinio --set global.domain=172.26.0.2.sslip.io --set global.tlsIssuer=letsencrypt-epinio  --values values.yaml
```

Being the **value.yaml** like this:
```
api:
  # Default users
  users:
    - username: admin
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: admin
    - username: epinio
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: user
    - username: user1_Hell@World 
      passwordBcrypt: "$2y$10$xrZYXonrAnklLCURDX2zu.HacO02Fflp5toM/riJ028aNS2PJRutS"
      role: user
    - username: user2_Hell#@~%/=World 
      passwordBcrypt: "$2y$10$I3/6py4jE4.P5IO1lWKg5e7D3.WQ8JKPX0kHTgPQPjW/h59utwzo6"
      role: user
  workspaces:
    - workspace

```

The idea is rather to create a Cypress scenario where helm gets upgraded like that, simply to add these parameters in during the Epinio installation.
