### ISSUE TITLE
[Cypress]  Expand e2e UI testing to Mac and Windows

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#234]
We should try run our UI e2e in different OS (Linux, MacOS and Windows)
A possible solution to study is using matrix with Github Actions. Something like this:

```
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [12, 14, 16]
        include:
          - os: windows-latest
            version: 17
```

Source link: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
