### ISSUE TITLE
[Cypress] Add test for login username with numbers

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#248]
Add to Cypress test automation for https://github.com/epinio/epinio/issues/1728

Basically, user `111111` should be able to login in the UI given: 

```yaml
api:
  # Default users
  users:
    #password: admin
    - username: "111111"
      passwordBcrypt: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
      role: user
      workspaces:
        - workspace
```
