### ISSUE TITLE
[Cypress] - Investigate if action step 'Checkout Rancher Dashboard repository' is needed in master_std_ui.yaml

### ISSUE THREAD

**Issue by mmartin24** [epinio/epinio-end-to-end-tests#251]
Task:

Investigate if this block is needed in `.github/workflows/master_std_ui.yml` for the Cyrpess tests workflow or can be removed:

```yaml
 - name: Checkout Rancher Dashboard repository
        uses: actions/checkout@v3
        with:
          repository: rancher/dashboard
          # Momentarily freezing latest version until epinio-dev is stable
          # https://github.com/epinio/epinio-end-to-end-tests/issues/247
          # ref: epinio-dev
          ref: epinio-standalone-v1.2.0.0.0.1
          path: dashboard
```
